
/**
 *
 * @author JSU
 */
public class PopUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form popUpFrame
     * @param ip
     * @param sendr
     * @param typ
     * @param cond
     * @param instr
     */
    public PopUpFrame(String ip, String sendr, String typ, String cond, String instr) {
        initComponents();
        senderName.setText(sendr);
        sourceIp.setText(ip);
        ensType.setText(typ);
        ensConditionText.setText(cond);
        ensInstructionText.setText(instr);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ensTitleLabel = new javax.swing.JLabel();
        sourceInfoLabel = new javax.swing.JLabel();
        senderNameLabel = new javax.swing.JLabel();
        senderName = new javax.swing.JLabel();
        sourceIpLabel = new javax.swing.JLabel();
        sourceIp = new javax.swing.JLabel();
        ensTypeLabel = new javax.swing.JLabel();
        ensType = new javax.swing.JLabel();
        ensConditionLabel = new javax.swing.JLabel();
        ensScrollPaneOne = new javax.swing.JScrollPane();
        ensConditionText = new javax.swing.JTextPane();
        ensInstructionLabel = new javax.swing.JLabel();
        ensScrollPaneTwo = new javax.swing.JScrollPane();
        ensInstructionText = new javax.swing.JTextPane();
        dismissButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emergency Multicast Message System");
        setName("EMMSFrame"); // NOI18N
        setResizable(false);

        ensTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ensTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ensTitleLabel.setText("Emergency Notification System");

        sourceInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sourceInfoLabel.setText("Source Information");

        senderNameLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        senderNameLabel.setText("Name of Sender:");

        sourceIpLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sourceIpLabel.setText("Source IP:");

        ensTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ensTypeLabel.setText("Type:");

        ensConditionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ensConditionLabel.setText("Condition");

        ensConditionText.setEditable(false);
        ensScrollPaneOne.setViewportView(ensConditionText);

        ensInstructionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ensInstructionLabel.setText("Instructions");

        ensInstructionText.setEditable(false);
        ensScrollPaneTwo.setViewportView(ensInstructionText);

        dismissButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dismissButton.setMnemonic('D');
        dismissButton.setText("Dismiss");
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ensTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addComponent(ensScrollPaneOne)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceInfoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(senderNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(senderName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(sourceIpLabel)
                                .addGap(18, 18, 18)
                                .addComponent(sourceIp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ensTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ensType, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ensConditionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ensInstructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ensScrollPaneTwo))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(dismissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ensTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sourceInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senderNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senderName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sourceIpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourceIp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ensTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ensType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ensConditionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ensScrollPaneOne, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ensInstructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ensScrollPaneTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dismissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_dismissButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dismissButton;
    private javax.swing.JLabel ensConditionLabel;
    private javax.swing.JTextPane ensConditionText;
    private javax.swing.JLabel ensInstructionLabel;
    private javax.swing.JTextPane ensInstructionText;
    private javax.swing.JScrollPane ensScrollPaneOne;
    private javax.swing.JScrollPane ensScrollPaneTwo;
    private javax.swing.JLabel ensTitleLabel;
    private javax.swing.JLabel ensType;
    private javax.swing.JLabel ensTypeLabel;
    private javax.swing.JLabel senderName;
    private javax.swing.JLabel senderNameLabel;
    private javax.swing.JLabel sourceInfoLabel;
    private javax.swing.JLabel sourceIp;
    private javax.swing.JLabel sourceIpLabel;
    // End of variables declaration//GEN-END:variables
}
